---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-b
spec:
  replicas: 1
  selector:
    matchLabels:
      application: metrics-b
  template:
    metadata:
      labels:
        application: metrics-b
    spec:
      containers:
        - image: quay.io/skupper/simple-prom-metrics:v2
          name: metrics-b
          imagePullPolicy: IfNotPresent
---
